apiVersion: v1
kind: Pod
metadata:
  name: busybox-sleep
  labels:
    app: busybox-sleep
spec:
  nodeSelector:
    node: VM2
  volumes:
    - name: ipfs-data
          # persistentVolumeClaim:
          #   claimName: mypvc
      hostPath:
        path: /ipfs  # Path on the node's local filesystem
        type: DirectoryOrCreate
  containers:
  - name: busybox-container
    image: busybox
    command: ["sleep", "3600"]
    resources:
      limits:
        memory: "64Mi"
        cpu: "100m"
  restartPolicy: Never
