apiVersion: v1
kind: Pod
metadata:
  name: busybox-sleep
  labels:
    app: busybox-sleep
spec:
  nodeSelector:
    node: VM3
  containers:
  - name: busybox-container
    image: busybox
    command: ["sleep", "3600"]
    resources:
      limits:
        memory: "64Mi"
        cpu: "100m"
  restartPolicy: Never
