--- #---------------- Chaincode Service ---------------------
apiVersion: v1
kind: Service
metadata:
  name: bel-dealer
  labels:
    app: bel-dealer
spec:
  ports:
    - name: grpc
      port: 7052
      targetPort: 7052
  selector:
    app: chaincode-bel-dealer
