--- #---------------- Chaincode Service ---------------------
apiVersion: v1
kind: Service
metadata:
  name: automobile-dealer
  labels:
    app: automobile-dealer
spec:
  ports:
    - name: grpc
      port: 7052
      targetPort: 7052
  selector:
    app: chaincode-automobile-dealer
