---
#---------------- Chaincode Deployment ---------------------
apiVersion: apps/v1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: chaincode-automobile-manufacturer
  labels:
    app: chaincode-automobile-manufacturer
spec:
  selector:
    matchLabels:
      app: chaincode-automobile-manufacturer
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: chaincode-automobile-manufacturer
    spec:
      containers:
        - image: abhithshaji/automobile:3.3
          imagePullPolicy: Always
          name: chaincode-automobile-manufacturer
          env:
            - name: CHAINCODE_ID
              value: "automobile:694edcc5e2baea977bd03b4987429ba77663f2748cb308b40bc7846a3b3c040d"
            - name: CHAINCODE_SERVER_ADDRESS
              value: "0.0.0.0:7052"
          ports:
            - containerPort: 7052
          resources:
            limits:
              memory: "300Mi"
              cpu: "70m"
            requests:
              memory: "200Mi"
              cpu: "60m"
