apiVersion: v1
kind: Secret
metadata:
  name: secret-config
type: Opaque
data:
  cluster-secret: NzAzOTcyZjE4MmZmYTVkZmU5MDA1ZjlkOWRmMTJjZGM1N2FjZmMwMDUyZjdlNmYwMmQ1ZDg5MmRlM2Q3MTMxNg==
  bootstrap-cluster-priv-key: Q0FFU1FNS0s2QzRqaEllUE9YZWgyMXBqczdkSXMvaWtwalJ6bWlmYitkVnNnKzZ6UEZXMksyMElXRkJDZ0ZUVVJJWkp1ajEweUtVd0J0MVJDUjJDa2t4MmYvWT0K
  swarmkey: L2tleS9zd2FybS9wc2svMS4wLjAvCi9iYXNlMTYvCjk2NGIxZjkwZmM0M2E0ODFkYmU2NzM3NWIzZjNjMzJmYjU5NmE4MmIyNTRhZGRmOGVhNmU3YWIyMzEzYzkxNTcK
  bootstrap-peer-priv-key: Q0FFU1FCcmNqUjBqQ0s5M3NES0Z2OThFazViRHZsc2w1WlhUZXdUSEdIWi94VVh3S2dIdjVISm9HU0E3d3NxV3lyVmZHQytMeE9DVmhndWlxcmRtakNTeGsyZz0K