apiVersion: v1
kind: Service
metadata:
  name: ca-mvd
  
  labels:
    app: ca-mvd
spec:
  type: ClusterIP
  selector:
    app: ca-mvd
  ports:
    - protocol: TCP
      targetPort: 9054
      port: 9054