apiVersion: v1
kind: Service
metadata:
  name: ca-manufacturer
  labels:
    app: ca-manufacturer
spec:
  type: ClusterIP
  selector:
    app: ca-manufacturer
  ports:
    - protocol: TCP
      targetPort: 7054
      port: 7054