apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderer3
spec:
  selector:
    matchLabels:
      name: orderer3
  replicas: 1
  template:
    metadata:
      labels:
        name: orderer3
    spec:
      nodeSelector:
        org3: mvd 
      volumes:
        - name: fabricfiles
          # persistentVolumeClaim:
          #   claimName: mypvc
          hostPath:
            path: /mnt/fabric  # Directory on the node's filesystem
            type: DirectoryOrCreate
        - name: certbackup
          persistentVolumeClaim:
            claimName: mypvc
      initContainers:
      - name: copy-certificates
        image: busybox  # A lightweight image for copying files
        command: ['sh', '-c', 'cp -r /organizations /fabricbackup/organizations']
        volumeMounts:
          - name: fabricfiles
            mountPath: /organizations  # Mount the source (host path)
          - name: mypvc
            mountPath: /fabricbackup  # Mount the NFS destination
      containers:
        - image: hyperledger/fabric-orderer:2.5.4
          name: orderer3
          imagePullPolicy: IfNotPresent
          env:
            # - name: CONFIGTX_ORDERER_ADDRESSES
            #   value: "orderer3:7050"
            - name: ORDERER_GENERAL_LISTENADDRESS
              value: "0.0.0.0"
            - name: ORDERER_GENERAL_LISTENPORT
              value: "7050"
            - name: ORDERER_GENERAL_LOGLEVEL
              value: debug
            - name: ORDERER_GENERAL_LOCALMSPDIR
              value: /organizations/ordererOrganizations/auto.com/orderers/orderer3.auto.com/msp
            - name: ORDERER_GENERAL_LOCALMSPID
              value: OrdererMSP
            # - name: ORDERER_GENERAL_GENESISMETHOD
            #   value: file
            # - name: ORDERER_GENERAL_GENESISFILE
            #   value: /channel-artifacts/autochannel.block
            - name: ORDERER_GENERAL_TLS_ENABLED
              value: "true"
            - name: ORDERER_GENERAL_TLS_PRIVATEKEY
              value: /organizations/ordererOrganizations/auto.com/orderers/orderer3.auto.com/tls/server.key
            - name: ORDERER_GENERAL_TLS_CERTIFICATE
              value: /organizations/ordererOrganizations/auto.com/orderers/orderer3.auto.com/tls/server.crt
            - name: ORDERER_GENERAL_TLS_ROOTCAS
              value: /organizations/ordererOrganizations/auto.com/orderers/orderer3.auto.com/tls/ca.crt
            - name: ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY
              value: /organizations/ordererOrganizations/auto.com/orderers/orderer3.auto.com/tls/server.key
            - name: ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE
              value: /organizations/ordererOrganizations/auto.com/orderers/orderer3.auto.com/tls/server.crt
            - name: ORDERER_GENERAL_BOOTSTRAPMETHOD
              value: none
            - name: ORDERER_CHANNELPARTICIPATION_ENABLED
              value: "true"
            - name: ORDERER_ADMIN_TLS_ENABLED
              value: "true"
            - name: ORDERER_ADMIN_TLS_CERTIFICATE
              value: /organizations/ordererOrganizations/auto.com/orderers/orderer3.auto.com/tls/server.crt
            - name: ORDERER_ADMIN_TLS_PRIVATEKEY
              value: /organizations/ordererOrganizations/auto.com/orderers/orderer3.auto.com/tls/server.key
            - name: ORDERER_ADMIN_TLS_CLIENTROOTCAS
              value: /organizations/ordererOrganizations/auto.com/orderers/orderer3.auto.com/tls/ca.crt
            - name: ORDERER_ADMIN_TLS_ROOTCAS
              value: /organizations/ordererOrganizations/auto.com/orderers/orderer3.auto.com/tls/ca.crt
            - name: ORDERER_ADMIN_LISTENADDRESS
              value: 0.0.0.0:7051
            # - name: ORDERER_OPERATIONS_LISTENADDRESS
            #   value: 0.0.0.0:9443
            # - name: ORDERER_METRICS_PROVIDER
            #   value: prometheus

          resources:
            limits:
              memory: "250Mi"
              cpu: "90m"
            requests:
              memory: "200Mi"
              cpu: "80m"

          volumeMounts:
            - name: fabricfiles
              mountPath: /organizations
              subPath: organizations

            # - name: fabricfiles
            #   mountPath: /system-genesis-block
            #   subPath: system-genesis-block

            - name: fabricfiles
              mountPath: /channel-artifacts
              subPath: channel-artifacts

            - name: fabricfiles
              mountPath: /configtx
              subPath: configtx

            - name: fabricfiles
              mountPath: /scripts
              subPath: scripts
