apiVersion: apps/v1
kind: Deployment
metadata:
  name: cli-peer0-manufacturer
spec:
  selector:
    matchLabels:
      name: cli-peer0-manufacturer
  template:
    metadata:
      labels:
        name: cli-peer0-manufacturer
    spec:
      nodeSelector:
        org1: manufacturer
      volumes:
        - name: fabricfiles
          # persistentVolumeClaim:
          #   claimName: mypvc
          hostPath:
            path: /mnt/fabric  # Path on the node's local filesystem
            type: DirectoryOrCreate

      containers:
        - name: cli-peer0-manufacturer
          stdin: true
          tty: true
          resources:
            limits:
              memory: "300Mi"
              cpu: "70m"
            requests:
              memory: "200Mi"
              cpu: "50m"
          image: hyperledger/fabric-tools:2.5.4
          workingDir: /
          env:
            - name: ORDERER_CA
              value: /organizations/ordererOrganizations/auto.com/orderers/orderer.auto.com/msp/tlscacerts/tlsca.auto.com-cert.pem
            - name: CORE_PEER_ADDRESS
              value: peer0-manufacturer:7051
            - name: CORE_PEER_ID
              value: cli.peer0.manufacturer.auto.com
            - name: CORE_PEER_LOCALMSPID
              value: ManufacturerMSP
            - name: CORE_PEER_MSPCONFIGPATH
              value: /organizations/peerOrganizations/manufacturer.auto.com/users/Admin@manufacturer.auto.com/msp
            - name: CORE_PEER_TLS_CERT_FILE
              value: /organizations/peerOrganizations/manufacturer.auto.com/peers/peer0.manufacturer.auto.com/tls/server.crt
            - name: CORE_PEER_TLS_ENABLED
              value: "true"
            - name: CORE_PEER_TLS_KEY_FILE
              value: /organizations/peerOrganizations/manufacturer.auto.com/peers/peer0.manufacturer.auto.com/tls/server.key
            - name: CORE_PEER_TLS_ROOTCERT_FILE
              value: /organizations/peerOrganizations/manufacturer.auto.com/peers/peer0.manufacturer.auto.com/tls/ca.crt
            # - name: FABRIC_LOGGING_SPEC
            #   value: ERROR
            - name: GOPATH
              value: /opt/gopath
            # - name: SYS_CHANNEL
            #   value: system-channel
            - name: CORE_CHAINCODE_BUILDER
              value: hyperledger/fabric-ccenv:2.5.4
            - name: FABRIC_LOGGING_SPEC
              value: DEBUG
          volumeMounts:
            - mountPath: /organizations
              name: fabricfiles
              subPath: organizations
            - mountPath: /configtx
              name: fabricfiles
              subPath: configtx
            - mountPath: /channel-artifacts
              name: fabricfiles
              subPath: channel-artifacts
            - mountPath: /scripts
              name: fabricfiles
              subPath: scripts
            - mountPath: /opt/gopath/src/github.com/chaincode
              name: fabricfiles
              subPath: chaincode
          
