apiVersion: apps/v1
kind: Deployment
metadata:
  name: peer0-manufacturer
spec:
  selector:
    matchLabels:
      name: peer0-manufacturer
  replicas: 1
  template:
    metadata:
      labels:
        name: peer0-manufacturer
    spec:
      nodeSelector:
        node: VM2
      volumes:
        - name: fabricfiles
          # persistentVolumeClaim:
          #   claimName: mypvc
          hostPath:
            path: /mnt/fabric  # Path on the node's local filesystem
            type: DirectoryOrCreate
        - name: certbackup
          persistentVolumeClaim:
            claimName: mypvc
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
        - name: builders-config
          configMap:
            name: builders-config
            items:
              - key: core.yaml
                path: core.yaml
        - name: external-builder-detect
          configMap:
            name: builders-config
            items:
              - key: detect
                path: detect
                mode: 0544
        - name: external-builder-build
          configMap:
            name: builders-config
            items:
              - key: build
                path: build
                mode: 0544
        - name: external-builder-release
          configMap:
            name: builders-config
            items:
              - key: release
                path: release
                mode: 0544
      initContainers:
      - name: copy-certificates
        image: busybox  # A lightweight image for copying files
        command: ['sh', '-c', 'cp -r /organizations/* /fabricbackup/organizations']
        volumeMounts:
          - name: fabricfiles
            mountPath: /organizations  # Mount the source (host path)
            subPath: organizations
          - name: certbackup
            mountPath: /fabricbackup  # Mount the NFS destination
            subPath: fabricbackup
      containers:
        - name: peer
          image: hyperledger/fabric-peer:2.5.4
          command: ["sh", "-c", "peer node start"]
          env:
            - name: CORE_PEER_ADDRESSAUTODETECT
              value: "true"
            - name: CORE_PEER_ID
              value: peer0-manufacturer
            - name: CORE_PEER_ADDRESS
              value: peer0-manufacturer:7051
            - name: CORE_PEER_LISTENADDRESS
              value: 0.0.0.0:7051
            - name: CORE_PEER_EVENTS_ADDRESS
              value: 0.0.0.0:7061
            - name: CORE_PEER_GOSSIP_BOOTSTRAP
              value: peer0-manufacturer:7051
            - name: CORE_PEER_GOSSIP_ENDPOINT
              value: peer0-manufacturer:7051
            - name: CORE_PEER_GOSSIP_EXTERNALENDPOINT
              value: peer0-manufacturer:7051
            - name: CORE_PEER_GOSSIP_ORGLEADER
              value: "true"
            - name: CORE_PEER_GOSSIP_USELEADERELECTION
              value: "false"
            - name: CORE_PEER_PROFILE_ENABLED
              value: "true"
            - name: CORE_PEER_LOCALMSPID
              value: ManufacturerMSP
            - name: CORE_PEER_MSPCONFIGPATH
              value: /organizations/peerOrganizations/manufacturer.auto.com/peers/peer0.manufacturer.auto.com/msp
            - name: FABRIC_LOGGING_SPEC
              value: debug
            - name: CORE_PEER_TLS_ENABLED
              value: "true"
            - name: CORE_PEER_TLS_CERT_FILE
              value: /organizations/peerOrganizations/manufacturer.auto.com/peers/peer0.manufacturer.auto.com/tls/server.crt
            - name: CORE_PEER_TLS_KEY_FILE
              value: /organizations/peerOrganizations/manufacturer.auto.com/peers/peer0.manufacturer.auto.com/tls/server.key
            - name: CORE_PEER_TLS_ROOTCERT_FILE
              value: /organizations/peerOrganizations/manufacturer.auto.com/peers/peer0.manufacturer.auto.com/tls/ca.crt
            - name: CORE_LEDGER_STATE_STATEDATABASE
              value: "CouchDB"
            - name: CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS
              value: "localhost:5984"
            - name: FABRIC_CFG_PATH
              value: /etc/hyperledger/fabric
            - name: CORE_OPERATIONS_LISTENADDRESS
              value: 0.0.0.0:9443
            - name: CORE_METRICS_PROVIDER
              value: prometheus
            - name: CORE_CHAINCODE_BUILDER
              value: hyperledger/fabric-ccenv:2.5.4
          ports:    
            - containerPort: 7051
            - containerPort: 7052
            - containerPort: 7053
            - containerPort: 9443
          resources:
            limits:
              memory: "300Mi"
              cpu: "80m"
            requests:
              memory: "200Mi"
              cpu: "60m"
          volumeMounts:
            - mountPath: /opt/gopath/src/github.com/chaincode/
              name: fabricfiles
              subPath: chaincode/
            - mountPath: /organizations
              name: fabricfiles
              subPath: organizations
            - name: fabricfiles
              mountPath: /scripts
              subPath: scripts
            - mountPath: /channel-artifacts
              name: certbackup
              subPath: channel-artifacts
            - mountPath: /var/hyperledger/production
              name: fabricfiles
              subPath: state/manufacturer/peer0
            - mountPath: /etc/hyperledger/fabric/core.yaml
              name: builders-config
              subPath: core.yaml
            - mountPath: /opt/hyperledger/ccaas_builder/bin/detect
              name: external-builder-detect
              subPath: detect
            - mountPath: /opt/hyperledger/ccaas_builder/bin/build
              name: external-builder-build
              subPath: build
            - mountPath: /opt/hyperledger/ccaas_builder/bin/release
              name: external-builder-release
              subPath: release
            - mountPath: /var/run/docker.sock
              name: docker-socket
            
            

        - name: couchdb
          image: hyperledger/fabric-couchdb:0.4.15
          resources:
            limits:
              memory: "300Mi"
              cpu: "80m"
            requests:
              memory: "200Mi"
              cpu: "60m"
          volumeMounts:
            - mountPath: /var/lib/couchdb
              name: fabricfiles
              subPath: state/manufacturer/peer0-couchdb
