apiVersion: batch/v1
kind: Job
metadata:
  name: create-certs-orderer2
spec:
  parallelism: 1
  completions: 1
  template:
    metadata:
      name: create-certs-ord2
    spec:
      nodeSelector:
        org0: orderer2
      volumes:
        - name: fabricfiles
          # persistentVolumeClaim:
          #   claimName: mypvc
          hostPath:
            path: /mnt/fabric  # Directory on the node's filesystem
            type: DirectoryOrCreate
        # - name: nfs
        #   persistentVolumeClaim:
        #     claimName: mypvc
      containers:
        - name: create-certs
          image: hyperledger/fabric-ca-tools:1.2.1
          resources:
            requests:
              memory: "300Mi"
              cpu: "200m"
            limits:
              memory: "500Mi"
              cpu: "250m"
          volumeMounts:
            - mountPath: /organizations
              name: fabricfiles
              subPath: organizations
            - mountPath: /scripts
              name: fabricfiles
              subPath: scripts
          command:
            - /bin/sh
            - -c
            - |
              ./scripts/orderer2-certs.sh
      restartPolicy: Never
