apiVersion: batch/v1
kind: Job
metadata:
  name: create-certs-manufacturer
spec:
  parallelism: 1
  completions: 1
  template:
    metadata:
      name: create-certs-manu
    spec:
      nodeSelector:
        org1: manufacturer
      volumes:
        - name: fabricfiles
          # persistentVolumeClaim:
          #   claimName: mypvc
          hostPath:
            path: /mnt/fabric  # Directory on the node's filesystem
            type: DirectoryOrCreate
        # - name: scripts
        #   persistentVolumeClaim:
        #     claimName: mypvc
      initContainers:
        - name: set-permissions
          image: busybox  # Lightweight image for running commands
          command:
            - /bin/sh
            - -c
            - |
              chmod +x /scripts -R  
          volumeMounts:
            - mountPath: /scripts
              name: fabricfiles
              subPath: scripts  # Ensure the script is mounted here
      containers:
        - name: create-certs
          image: hyperledger/fabric-ca-tools:1.2.1
          resources:
            requests:
              memory: "300Mi"
              cpu: "200m"
            limits:
              memory: "500Mi"
              cpu: "250m"
          volumeMounts:
            - mountPath: /organizations
              name: fabricfiles
              subPath: organizations
            - mountPath: /scripts
              name: fabricfiles
              subPath: scripts
          command:
            - /bin/sh
            - -c
            - |
              ./scripts/manufacturer-certs.sh
      restartPolicy: Never
